version: '3.8'

services:
  oauth2-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
      - DB_TYPE=sqlite
      - DB_PATH=/app/data/oauth2.db
    volumes:
      - oauth2_data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - oauth2-network

  oauth2-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - GIN_MODE=release
    depends_on:
      - oauth2-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - oauth2-network

volumes:
  oauth2_data:
    driver: local

networks:
  oauth2-network:
    driver: bridge
